# Generated by Django 4.0.6 on 2022-07-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='contetnt',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='ctreated_at',
            new_name='created_at',
        ),
    ]
